version: '3'

services:

  # Laravel service
  backend:
    build: ./backend
    container_name: powerclonic-api
    ports:
      - "7000:80"
    volumes:
      - "./backend:/var/www/html"
      - "/var/www/env/powerclonicxyz.env:/var/www/html/.env"
    networks:
      - powerclonic-network
      - root-network

  # Node service
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
      args:
        - "VUE_APP_BASE_API=https://api.powerclonic.xyz"
    volumes:
      - "./frontend:/app"
    container_name: powerclonic-frontend
    ports: 
      - "7070:80"
    networks:
      - powerclonic-network

networks:
  powerclonic-network:
    driver: bridge
  root-network:
    external: true
